name: Push 🐲

on:
  push: {}
  schedule:
    - cron: '0 18 * * 5'

jobs:
  checks:
    uses: nzbr/actions/.github/workflows/run_checks.yml@main
    secrets:
      SECRET_DECRYPTION_KEY: ${{ secrets.SECRET_DECRYPTION_KEY }}

  build:
    name: Build Copperflame 🔥
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drv:
          - copperflame
          - copperflame-mono
          - copperflame-mono.unpatched
          - devShells.x86_64-linux.default
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Nix Build ❄️
        uses: nzbr/actions/nix-build@main
        with:
          expression: .#${{ matrix.drv }}
          cache: true
          cache-tag: ${{ matrix.drv }}
          secret-key: ${{ secrets.SECRET_DECRYPTION_KEY }}
